### ISSUE TITLE
Github repo structure

### ISSUE THREAD

**Issue by KatyaRyazantseva** [wiepteam/studygroup#2]
Let's discuss here the structure of the repo. What folders we need. Here is a draft:

- Cohorts
    - Cohort 1
    - Cohort 2
- Meetings
- Materials (our google doc, etc)
- Program-guide
  - Program-details
  - Github-repo-guide

Feel free to share your ideas.

**Comment by aslikaya** [comment]
Hey, looks good! Maybe putting meetings under the relevant cohort folder could be considered
