### ISSUE TITLE
Weekly Call [Cohort 1]

### ISSUE THREAD

**Issue by poojaranjan** [wiepteam/studygroup#4]
# Agenda

### Info
Date & Time: Aug 9, 2024 at 12:00 UTC
Meeting link: https://app.huddle01.com/emx-kqna-lbw

### Open PRs for Review
- [ ] https://github.com/ethereum/eipw/pull/99
- [ ] https://github.com/ethereum/eipw/pull/98
- [ ] https://github.com/ethereum/eipw/pull/101

### Info on Cohort 2
[Announcement](https://github.com/wiepteam/studygroup/tree/main/Cohort%202)

### Q&A

(Please add links in comments )

**Comment by aslikaya** [comment]
Can we add this https://github.com/ethereum/eipw/pull/101 ? I was waiting for a response
